require("./config/preload")
const express = require("express")
const cors = require("cors")
const helmet = require("helmet")
const router = require("./router")
const { config } = require("./config")
const { createApplication } = require("./core")

createApplication(express())
  .useMiddleware(cors())
  .useMiddleware(helmet())
  .useMiddleware(express.json())
  .useRouter("/", router)
  .start(config.port, `Server was started on http://localhost:${config.port}`)
